[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-args=-rdynamic"]

[target.x86_64-apple-darwin]
rustflags = ["-Clink-args=-rdynamic"]

[target.wasm64-unknown-unknown]
linker = "emcc"
ar = "emar"

[target.wasm32-unknown-emscripten]
linker = "emcc"
ar = "emar"
# previous max memory 536870912
rustflags = [
    "-Clink-arg=-O3",
#    "-Clink-arg=-g",
    "-Clink-arg=src/ao_log.c",
    "-Clink-arg=src/weavedrive.c",
    "-Clink-arg=--pre-js", "-Clink-arg=build/pre.js",
    "-Clink-arg=-sASYNCIFY=1",
    "-Clink-arg=-sALLOW_MEMORY_GROWTH=1",
    "-Clink-arg=-sINITIAL_MEMORY=134217728",
    "-Clink-arg=-sMAXIMUM_MEMORY=1073741824",
    "-Clink-arg=-sMODULARIZE=1",
    "-Clink-arg=-sDETERMINISTIC=1",
    "-Clink-arg=-sASSERTIONS=1",
    "-Clink-arg=-sNODERAWFS=0",
    "-Clink-arg=-sFORCE_FILESYSTEM=1",
    "-Clink-arg=-lm",
    "-Clink-arg=-ldl",
    "-Clink-arg=-sEXPORTED_RUNTIME_METHODS=cwrap",
    "-Clink-arg=-obuild/transformers_ao.js",
]
