[target.wasm32-unknown-emscripten]
linker = "emcc"
rustflags = [
  """-Clink-args=
  -O3 -sWASM=1 -sEXPORTED_FUNCTIONS=["_handle"]
  -o process.js
  -sMODULARIZE
  -sASSERTIONS
  -sEXPORTED_RUNTIME_METHODS=["cwrap"]
  """
]
